version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: yungsergo
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mkdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: